### ISSUE TITLE
mpl, эпизод 2, фантомный gif

### ISSUE THREAD

**Issue by avasyukov** [Grongr/python_3sem_labs#1]
Я уловил идею вот этого кода:
https://github.com/Grongr/python_3sem_labs/blob/45233789074c1bbfdce848fc4fe4149b779e5fc3/matplot/matplot_lab.py#L88-L102

Но всё же не надо так шамански и средствами ОС делать штатную штуку. Потому что, например, у меня оно ещё и не сработало (linux, но xviewer нет) - в итоге ни картинки на экране, ни сохранённых файлов.

Можно просто убрать этот кусок и сохранить или показать независимые кадры - будет ок. Можно показать анимацию средствами mpl.

**Comment by Grongr** [comment]
Понял, сделаю

**Comment by Grongr** [comment]
Сделал сохранение картинки и отображение ее через матплотлиб
